# pulling nodejsapp image from dockerhub and deploying and creating service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp
  labels:
    app: employee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
      - name: employee
        image: devopsedu/employee
#service type Nodeport for JSapp 
---
apiVersion: v1
kind: Service
metadata:
  name: mynodejs
spec:
  type: NodePort
  selector:
    app: employee
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888


